version: '3'

services:
  php:
    build:
      context: ./docker/php
    ports:
    - 9000:9000
    volumes:
    - ./html/:/var/www/html
    - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    - ./docker/php/php-ini:/usr/local/etc/php/custom.d
    working_dir: /var/www/html/api/public
    environment:
      PHP_INI_SCAN_DIR: "/usr/local/etc/php/custom.d:/usr/local/etc/php/conf.d"
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_CHARSET: ${DB_CHARSET}
      DB_COLLATION: ${DB_COLLATION}

  nginx:
    image: nginx:1.13.8
    ports:
    - 8000:80
    - 443:443
    volumes:
    - ./html/:/var/www/html
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - php

  mysql:
    image: mysql:5.7
    ports:
    - 3306:3306
    depends_on:
    - php
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
